spring:
  application:
    name: DDD-Hexagonal-Example

  datasource:
    url: jdbc:h2:mem:order
    username: sa
    password:
  jpa:
    database: H2
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
    show-sql: true
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true